Markdown:
  WarnInvalid: true

Layout/CommentIndentation:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Layout/LeadingCommentSpace:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Layout/TrailingBlankLines:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Style/AsciiComments:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Style/Documentation:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Style/CommentAnnotation:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*.md'
    - '**/*.markdown'

Metrics/LineLength:
  IgnoredPatterns:
    - !ruby/regexp /^\#/
