name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-lint-${{ hashFiles('Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-lint-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle install
    - name: Run Rubocop
      run: |
        bundle exec rubocop
